
export enum NoteType {
  MEMO = 'MEMO',
  NUTRITION = 'NUTRITION',
  STEPS = 'STEPS',
  STEPS_TRACKER = 'STEPS_TRACKER',
  ALARM = 'ALARM',
  TIMER = 'TIMER',
}

export interface NutritionData {
  calories: number;
  carbs: number;
  protein: number;
  fat: number;
  foodName: string;
}

export interface AlarmData {
  time: string;
  label: string;
  fired?: boolean;
}

export interface StepsData {
  count: number;
  isLive?: boolean;
}

export interface Note {
  id: string;
  createdAt: Date;
  type: NoteType;
  content: string;
  imageUrl?: string; // Base64 or URL
  isAiImage?: boolean; // True if generated by AI, false/undefined if user uploaded
  nutrition?: NutritionData;
  alarm?: AlarmData;
  steps?: StepsData;
}

export interface ClassificationResult {
  type: NoteType;
  content: string;
  steps?: number;
  alarmTime?: string;
  alarmLabel?: string;
  nutrition?: NutritionData;
  visualDescription?: string;
}

export interface DraftData {
  content: string;
  type: NoteType;
  alarmTime?: string;
  stepsCount?: number;
  nutritionData?: NutritionData;
  visualDescription?: string;
}
